MAINSTAT_KEY_STRINGS = {
	"HP": "hp",
	"ATK": "atk",
	"DEF": "def",
	"CRIT Rate": "critRate",
	"CRIT DMG": "critDMG",
	"Energy Recharge": "enerRech",
	"Healing Bonus": "heal",
	"Elemental Mastery": "eleMas",
	"Physical DMG Bonus": "physical_dmg",
	"Anemo DMG Bonus": "anemo_dmg",
	"Geo DMG Bonus": "geo_dmg",
	"Electro DMG Bonus": "electro_dmg",
	"Hydro DMG Bonus": "hydro_dmg",
	"Pyro DMG Bonus": "pyro_dmg",
	"Cryo DMG Bonus": "cryo_dmg",
	"Dendro DMG Bonus": "dendro_dmg",
}

SUBSTAT_KEY_STRINGS = {
	"HP": "hp",
	"ATK": "atk",
	"DEF": "def",
	"CRIT Rate": "critRate",
	"CRIT DMG": "critDMG",
	"Energy Recharge": "enerRech",
	"Elemental Mastery": "eleMas",
}

SET_KEY_STRINGS = {
	"Adventurer": "Adventurer",
	"Archaic Petra": "ArchaicPetra",
	"Berserker": "Berserker",
	"Blizzard Strayer": "BlizzardStrayer",
	"Bloodstained Chivalry": "BloodstainedChivalry",
	"Brave Heart": "BraveHeart",
	"Crimson Witch of Flames": "CrimsonWitchOfFlames",
	"Deepwood Memories": "DeepwoodMemories",
	"Defender's Will": "DefendersWill",
	"Desert Pavilion Chronicle": "DesertPavilionChronicle",
	"Echoes of an Offering": "EchoesOfAnOffering",
	"Emblem of Severed Fate": "EmblemOfSeveredFate",
	"Flower of Paradise Lost": "FlowerOfParadiseLost",
	"Gambler": "Gambler",
	"Gilded Dreams": "GildedDreams",
	"Gladiator's Finale": "GladiatorsFinale",
	"Heart of Depth": "HeartOfDepth",
	"Husk of Opulent Dreams": "HuskOfOpulentDreams",
	"Instructor": "Instructor",
	"Lavawalker": "Lavawalker",
	"Lucky Dog": "LuckyDog",
	"Maiden Beloved": "MaidenBeloved",
	"Martial Artist": "MartialArtist",
	"Noblesse Oblige": "NoblesseOblige",
	"Nymph's Dream": "NymphsDream",
	"Ocean-Hued Clam": "OceanHuedClam",
	"Pale Flame": "PaleFlame",
	"Prayers for Destiny": "PrayersForDestiny",
	"Prayers for Illumination": "PrayersForIllumination",
	"Prayers for Wisdom": "PrayersForWisdom",
	"Prayers to Springtime": "PrayersToSpringtime",
	"Resolution of Sojourner": "ResolutionOfSojourner",
	"Retracing Bolide": "RetracingBolide",
	"Scholar": "Scholar",
	"Shimenawa's Reminiscence": "ShimenawasReminiscence",
	"Tenacity of the Millelith": "TenacityOfTheMillelith",
	"The Exile": "TheExile",
	"Thundering Fury": "ThunderingFury",
	"Thundersoother": "Thundersoother",
	"Tiny Miracle": "TinyMiracle",
	"Traveling Doctor": "TravelingDoctor",
	"Vermillion Hereafter": "VermillionHereafter",
	"Viridescent Venerer": "ViridescentVenerer",
	"Vourukasha's Glow": "VourukashasGlow",
	"Wanderer's Troupe": "WanderersTroupe",
}

NAME_SET_SLOT_KEY_STRINGS = {
	'AdventurersFlower': {'setKey': 'Adventurer', 'slotKey': 'flower'},
	'AdventurersTailFeather': {'setKey': 'Adventurer', 'slotKey': 'plume'},
	'AdventurersPocketWatch': {'setKey': 'Adventurer', 'slotKey': 'sands'},
	'AdventurersGoldenGoblet': {'setKey': 'Adventurer', 'slotKey': 'goblet'},
	'AdventurersBandana': {'setKey': 'Adventurer', 'slotKey': 'circlet'},
	'FlowerofCrevicedCliff': {'setKey': 'ArchaicPetra', 'slotKey': 'flower'},
	'FeatherofJaggedPeaks': {'setKey': 'ArchaicPetra', 'slotKey': 'plume'},
	'SundialofEnduringJade': {'setKey': 'ArchaicPetra', 'slotKey': 'sands'},
	'GobletofChiseledCrag': {'setKey': 'ArchaicPetra', 'slotKey': 'goblet'},
	'MaskofSolitudeBasalt': {'setKey': 'ArchaicPetra', 'slotKey': 'circlet'},
	'BerserkersRose': {'setKey': 'Berserker', 'slotKey': 'flower'},
	'BerserkersIndigoFeather': {'setKey': 'Berserker', 'slotKey': 'plume'},
	'BerserkersTimepiece': {'setKey': 'Berserker', 'slotKey': 'sands'},
	'BerserkersBoneGoblet': {'setKey': 'Berserker', 'slotKey': 'goblet'},
	'BerserkersBattleMask': {'setKey': 'Berserker', 'slotKey': 'circlet'},
	'SnowsweptMemory': {'setKey': 'BlizzardStrayer', 'slotKey': 'flower'},
	'IcebreakersResolve': {'setKey': 'BlizzardStrayer', 'slotKey': 'plume'},
	'FrozenHomelandsDemise': {'setKey': 'BlizzardStrayer', 'slotKey': 'sands'},
	'FrostWeavedDignity': {'setKey': 'BlizzardStrayer', 'slotKey': 'goblet'},
	'BrokenRimesEcho': {'setKey': 'BlizzardStrayer', 'slotKey': 'circlet'},
	'BloodstainedFlowerofIron': {'setKey': 'BloodstainedChivalry', 'slotKey': 'flower'},
	'BloodstainedBlackPlume': {'setKey': 'BloodstainedChivalry', 'slotKey': 'plume'},
	'BloodstainedFinalHour': {'setKey': 'BloodstainedChivalry', 'slotKey': 'sands'},
	'BloodstainedChevaliersGoblet': {'setKey': 'BloodstainedChivalry', 'slotKey': 'goblet'},
	'BloodstainedIronMask': {'setKey': 'BloodstainedChivalry', 'slotKey': 'circlet'},
	'MedaloftheBrave': {'setKey': 'BraveHeart', 'slotKey': 'flower'},
	'ProspectoftheBrave': {'setKey': 'BraveHeart', 'slotKey': 'plume'},
	'FortitudeoftheBrave': {'setKey': 'BraveHeart', 'slotKey': 'sands'},
	'OutsetoftheBrave': {'setKey': 'BraveHeart', 'slotKey': 'goblet'},
	'CrownoftheBrave': {'setKey': 'BraveHeart', 'slotKey': 'circlet'},
	'WitchsFlowerofBlaze': {'setKey': 'CrimsonWitchOfFlames', 'slotKey': 'flower'},
	'WitchsEverBurningPlume': {'setKey': 'CrimsonWitchOfFlames', 'slotKey': 'plume'},
	'WitchsEndTime': {'setKey': 'CrimsonWitchOfFlames', 'slotKey': 'sands'},
	'WitchsHeartFlames': {'setKey': 'CrimsonWitchOfFlames', 'slotKey': 'goblet'},
	'WitchsScorchingHat': {'setKey': 'CrimsonWitchOfFlames', 'slotKey': 'circlet'},
	'LabyrinthWayfarer': {'setKey': 'DeepwoodMemories', 'slotKey': 'flower'},
	'ScholarofVines': {'setKey': 'DeepwoodMemories', 'slotKey': 'plume'},
	'ATimeofInsight': {'setKey': 'DeepwoodMemories', 'slotKey': 'sands'},
	'LampoftheLost': {'setKey': 'DeepwoodMemories', 'slotKey': 'goblet'},
	'LaurelCoronet': {'setKey': 'DeepwoodMemories', 'slotKey': 'circlet'},
	'GuardiansFlower': {'setKey': 'DefendersWill', 'slotKey': 'flower'},
	'GuardiansSigil': {'setKey': 'DefendersWill', 'slotKey': 'plume'},
	'GuardiansClock': {'setKey': 'DefendersWill', 'slotKey': 'sands'},
	'GuardiansVessel': {'setKey': 'DefendersWill', 'slotKey': 'goblet'},
	'GuardiansBand': {'setKey': 'DefendersWill', 'slotKey': 'circlet'},
	'SoulscentBloom': {'setKey': 'EchoesOfAnOffering', 'slotKey': 'flower'},
	'JadeLeaf': {'setKey': 'EchoesOfAnOffering', 'slotKey': 'plume'},
	'SymbolofFelicitation': {'setKey': 'EchoesOfAnOffering', 'slotKey': 'sands'},
	'ChaliceoftheFont': {'setKey': 'EchoesOfAnOffering', 'slotKey': 'goblet'},
	'FlowingRings': {'setKey': 'EchoesOfAnOffering', 'slotKey': 'circlet'},
	'MagnificentTsuba': {'setKey': 'EmblemOfSeveredFate', 'slotKey': 'flower'},
	'SunderedFeather': {'setKey': 'EmblemOfSeveredFate', 'slotKey': 'plume'},
	'StormCage': {'setKey': 'EmblemOfSeveredFate', 'slotKey': 'sands'},
	'ScarletVessel': {'setKey': 'EmblemOfSeveredFate', 'slotKey': 'goblet'},
	'OrnateKabuto': {'setKey': 'EmblemOfSeveredFate', 'slotKey': 'circlet'},
	'GamblersBrooch': {'setKey': 'Gambler', 'slotKey': 'flower'},
	'GamblersFeatherAccessory': {'setKey': 'Gambler', 'slotKey': 'plume'},
	'GamblersPocketWatch': {'setKey': 'Gambler', 'slotKey': 'sands'},
	'GamblersDiceCup': {'setKey': 'Gambler', 'slotKey': 'goblet'},
	'GamblersEarrings': {'setKey': 'Gambler', 'slotKey': 'circlet'},
	'DreamingSteelbloom': {'setKey': 'GildedDreams', 'slotKey': 'flower'},
	'FeatherofJudgment': {'setKey': 'GildedDreams', 'slotKey': 'plume'},
	'TheSunkenYears': {'setKey': 'GildedDreams', 'slotKey': 'sands'},
	'HoneyedFinalFeast': {'setKey': 'GildedDreams', 'slotKey': 'goblet'},
	'ShadowoftheSandKing': {'setKey': 'GildedDreams', 'slotKey': 'circlet'},
	'GladiatorsNostalgia': {'setKey': 'GladiatorsFinale', 'slotKey': 'flower'},
	'GladiatorsDestiny': {'setKey': 'GladiatorsFinale', 'slotKey': 'plume'},
	'GladiatorsLonging': {'setKey': 'GladiatorsFinale', 'slotKey': 'sands'},
	'GladiatorsIntoxication': {'setKey': 'GladiatorsFinale', 'slotKey': 'goblet'},
	'GladiatorsTriumphus': {'setKey': 'GladiatorsFinale', 'slotKey': 'circlet'},
	'GildedCorsage': {'setKey': 'HeartOfDepth', 'slotKey': 'flower'},
	'GustofNostalgia': {'setKey': 'HeartOfDepth', 'slotKey': 'plume'},
	'CopperCompass': {'setKey': 'HeartOfDepth', 'slotKey': 'sands'},
	'GobletofThunderingDeep': {'setKey': 'HeartOfDepth', 'slotKey': 'goblet'},
	'WineStainedTricorne': {'setKey': 'HeartOfDepth', 'slotKey': 'circlet'},
	'BloomTimes': {'setKey': 'HuskOfOpulentDreams', 'slotKey': 'flower'},
	'PlumeofLuxury': {'setKey': 'HuskOfOpulentDreams', 'slotKey': 'plume'},
	'SongofLife': {'setKey': 'HuskOfOpulentDreams', 'slotKey': 'sands'},
	'CalabashofAwakening': {'setKey': 'HuskOfOpulentDreams', 'slotKey': 'goblet'},
	'SkeletalHat': {'setKey': 'HuskOfOpulentDreams', 'slotKey': 'circlet'},
	'InstructorsBrooch': {'setKey': 'Instructor', 'slotKey': 'flower'},
	'InstructorsFeatherAccessory': {'setKey': 'Instructor', 'slotKey': 'plume'},
	'InstructorsPocketWatch': {'setKey': 'Instructor', 'slotKey': 'sands'},
	'InstructorsTeaCup': {'setKey': 'Instructor', 'slotKey': 'goblet'},
	'InstructorsCap': {'setKey': 'Instructor', 'slotKey': 'circlet'},
	'LavawalkersResolution': {'setKey': 'Lavawalker', 'slotKey': 'flower'},
	'LavawalkersSalvation': {'setKey': 'Lavawalker', 'slotKey': 'plume'},
	'LavawalkersTorment': {'setKey': 'Lavawalker', 'slotKey': 'sands'},
	'LavawalkersEpiphany': {'setKey': 'Lavawalker', 'slotKey': 'goblet'},
	'LavawalkersWisdom': {'setKey': 'Lavawalker', 'slotKey': 'circlet'},
	'LuckyDogsClover': {'setKey': 'LuckyDog', 'slotKey': 'flower'},
	'LuckyDogsEagleFeather': {'setKey': 'LuckyDog', 'slotKey': 'plume'},
	'LuckyDogsHourglass': {'setKey': 'LuckyDog', 'slotKey': 'sands'},
	'LuckyDogsGoblet': {'setKey': 'LuckyDog', 'slotKey': 'goblet'},
	'LuckyDogsSilverCirclet': {'setKey': 'LuckyDog', 'slotKey': 'circlet'},
	'MaidensDistantLove': {'setKey': 'MaidenBeloved', 'slotKey': 'flower'},
	'MaidensHeartStrickenInfatuation': {'setKey': 'MaidenBeloved', 'slotKey': 'plume'},
	'MaidensPassingYouth': {'setKey': 'MaidenBeloved', 'slotKey': 'sands'},
	'MaidensFleetingLeisure': {'setKey': 'MaidenBeloved', 'slotKey': 'goblet'},
	'MaidensFadingBeauty': {'setKey': 'MaidenBeloved', 'slotKey': 'circlet'},
	'MartialArtistsRedFlower': {'setKey': 'MartialArtist', 'slotKey': 'flower'},
	'MartialArtistsFeatherAccessory': {'setKey': 'MartialArtist', 'slotKey': 'plume'},
	'MartialArtistsWaterHourglass': {'setKey': 'MartialArtist', 'slotKey': 'sands'},
	'MartialArtistsWineCup': {'setKey': 'MartialArtist', 'slotKey': 'goblet'},
	'MartialArtistsBandana': {'setKey': 'MartialArtist', 'slotKey': 'circlet'},
	'RoyalFlora': {'setKey': 'NoblesseOblige', 'slotKey': 'flower'},
	'RoyalPlume': {'setKey': 'NoblesseOblige', 'slotKey': 'plume'},
	'RoyalPocketWatch': {'setKey': 'NoblesseOblige', 'slotKey': 'sands'},
	'RoyalSilverUrn': {'setKey': 'NoblesseOblige', 'slotKey': 'goblet'},
	'RoyalMasque': {'setKey': 'NoblesseOblige', 'slotKey': 'circlet'},
	'SeaDyedBlossom': {'setKey': 'OceanHuedClam', 'slotKey': 'flower'},
	'DeepPalacesPlume': {'setKey': 'OceanHuedClam', 'slotKey': 'plume'},
	'CowryofParting': {'setKey': 'OceanHuedClam', 'slotKey': 'sands'},
	'PearlCage': {'setKey': 'OceanHuedClam', 'slotKey': 'goblet'},
	'CrownofWatatsumi': {'setKey': 'OceanHuedClam', 'slotKey': 'circlet'},
	'StainlessBloom': {'setKey': 'PaleFlame', 'slotKey': 'flower'},
	'WiseDoctorsPinion': {'setKey': 'PaleFlame', 'slotKey': 'plume'},
	'MomentofCessation': {'setKey': 'PaleFlame', 'slotKey': 'sands'},
	'SurpassingCup': {'setKey': 'PaleFlame', 'slotKey': 'goblet'},
	'MockingMask': {'setKey': 'PaleFlame', 'slotKey': 'circlet'},
	'TiaraofTorrents': {'setKey': 'PrayersForDestiny', 'slotKey': 'circlet'},
	'TiaraofFlame': {'setKey': 'PrayersForIllumination', 'slotKey': 'circlet'},
	'TiaraofThunder': {'setKey': 'PrayersForWisdom', 'slotKey': 'circlet'},
	'TiaraofFrost': {'setKey': 'PrayersToSpringtime', 'slotKey': 'circlet'},
	'HeartofComradeship': {'setKey': 'ResolutionOfSojourner', 'slotKey': 'flower'},
	'FeatherofHomecoming': {'setKey': 'ResolutionOfSojourner', 'slotKey': 'plume'},
	'SundialoftheSojourner': {'setKey': 'ResolutionOfSojourner', 'slotKey': 'sands'},
	'GobletoftheSojourner': {'setKey': 'ResolutionOfSojourner', 'slotKey': 'goblet'},
	'CrownofParting': {'setKey': 'ResolutionOfSojourner', 'slotKey': 'circlet'},
	'SummerNightsBloom': {'setKey': 'RetracingBolide', 'slotKey': 'flower'},
	'SummerNightsFinale': {'setKey': 'RetracingBolide', 'slotKey': 'plume'},
	'SummerNightsMoment': {'setKey': 'RetracingBolide', 'slotKey': 'sands'},
	'SummerNightsWaterballoon': {'setKey': 'RetracingBolide', 'slotKey': 'goblet'},
	'SummerNightsMask': {'setKey': 'RetracingBolide', 'slotKey': 'circlet'},
	'ScholarsBookmark': {'setKey': 'Scholar', 'slotKey': 'flower'},
	'ScholarsQuillPen': {'setKey': 'Scholar', 'slotKey': 'plume'},
	'ScholarsClock': {'setKey': 'Scholar', 'slotKey': 'sands'},
	'ScholarsInkCup': {'setKey': 'Scholar', 'slotKey': 'goblet'},
	'ScholarsLens': {'setKey': 'Scholar', 'slotKey': 'circlet'},
	'EntanglingBloom': {'setKey': 'ShimenawasReminiscence', 'slotKey': 'flower'},
	'ShaftofRemembrance': {'setKey': 'ShimenawasReminiscence', 'slotKey': 'plume'},
	'MorningDewsMoment': {'setKey': 'ShimenawasReminiscence', 'slotKey': 'sands'},
	'HopefulHeart': {'setKey': 'ShimenawasReminiscence', 'slotKey': 'goblet'},
	'CapriciousVisage': {'setKey': 'ShimenawasReminiscence', 'slotKey': 'circlet'},
	'FlowerofAccolades': {'setKey': 'TenacityOfTheMillelith', 'slotKey': 'flower'},
	'CeremonialWarPlume': {'setKey': 'TenacityOfTheMillelith', 'slotKey': 'plume'},
	'OrichalceousTimeDial': {'setKey': 'TenacityOfTheMillelith', 'slotKey': 'sands'},
	'NoblesPledgingVessel': {'setKey': 'TenacityOfTheMillelith', 'slotKey': 'goblet'},
	'GeneralsAncientHelm': {'setKey': 'TenacityOfTheMillelith', 'slotKey': 'circlet'},
	'ExilesFlower': {'setKey': 'TheExile', 'slotKey': 'flower'},
	'ExilesFeather': {'setKey': 'TheExile', 'slotKey': 'plume'},
	'ExilesPocketWatch': {'setKey': 'TheExile', 'slotKey': 'sands'},
	'ExilesGoblet': {'setKey': 'TheExile', 'slotKey': 'goblet'},
	'ExilesCirclet': {'setKey': 'TheExile', 'slotKey': 'circlet'},
	'ThunderbirdsMercy': {'setKey': 'ThunderingFury', 'slotKey': 'flower'},
	'SurvivorofCatastrophe': {'setKey': 'ThunderingFury', 'slotKey': 'plume'},
	'HourglassofThunder': {'setKey': 'ThunderingFury', 'slotKey': 'sands'},
	'OmenofThunderstorm': {'setKey': 'ThunderingFury', 'slotKey': 'goblet'},
	'ThunderSummonersCrown': {'setKey': 'ThunderingFury', 'slotKey': 'circlet'},
	'ThundersoothersHeart': {'setKey': 'Thundersoother', 'slotKey': 'flower'},
	'ThundersoothersPlume': {'setKey': 'Thundersoother', 'slotKey': 'plume'},
	'HourofSoothingThunder': {'setKey': 'Thundersoother', 'slotKey': 'sands'},
	'ThundersoothersGoblet': {'setKey': 'Thundersoother', 'slotKey': 'goblet'},
	'ThundersoothersDiadem': {'setKey': 'Thundersoother', 'slotKey': 'circlet'},
	'TinyMiraclesFlower': {'setKey': 'TinyMiracle', 'slotKey': 'flower'},
	'TinyMiraclesFeather': {'setKey': 'TinyMiracle', 'slotKey': 'plume'},
	'TinyMiraclesHourglass': {'setKey': 'TinyMiracle', 'slotKey': 'sands'},
	'TinyMiraclesGoblet': {'setKey': 'TinyMiracle', 'slotKey': 'goblet'},
	'TinyMiraclesEarrings': {'setKey': 'TinyMiracle', 'slotKey': 'circlet'},
	'TravelingDoctorsSilverLotus': {'setKey': 'TravelingDoctor', 'slotKey': 'flower'},
	'TravelingDoctorsOwlFeather': {'setKey': 'TravelingDoctor', 'slotKey': 'plume'},
	'TravelingDoctorsPocketWatch': {'setKey': 'TravelingDoctor', 'slotKey': 'sands'},
	'TravelingDoctorsMedicinePot': {'setKey': 'TravelingDoctor', 'slotKey': 'goblet'},
	'TravelingDoctorsHandkerchief': {'setKey': 'TravelingDoctor', 'slotKey': 'circlet'},
	'FloweringLife': {'setKey': 'VermillionHereafter', 'slotKey': 'flower'},
	'FeatherofNascentLight': {'setKey': 'VermillionHereafter', 'slotKey': 'plume'},
	'SolarRelic': {'setKey': 'VermillionHereafter', 'slotKey': 'sands'},
	'MomentofthePact': {'setKey': 'VermillionHereafter', 'slotKey': 'goblet'},
	'ThunderingPoise': {'setKey': 'VermillionHereafter', 'slotKey': 'circlet'},
	'InRemembranceofViridescentFields': {'setKey': 'ViridescentVenerer', 'slotKey': 'flower'},
	'ViridescentArrowFeather': {'setKey': 'ViridescentVenerer', 'slotKey': 'plume'},
	'ViridescentVenerersDetermination': {'setKey': 'ViridescentVenerer', 'slotKey': 'sands'},
	'ViridescentVenerersVessel': {'setKey': 'ViridescentVenerer', 'slotKey': 'goblet'},
	'ViridescentVenerersDiadem': {'setKey': 'ViridescentVenerer', 'slotKey': 'circlet'},
	'TroupesDawnlight': {'setKey': 'WanderersTroupe', 'slotKey': 'flower'},
	'BardsArrowFeather': {'setKey': 'WanderersTroupe', 'slotKey': 'plume'},
	'ConcertsFinalHour': {'setKey': 'WanderersTroupe', 'slotKey': 'sands'},
	'WanderersStringKettle': {'setKey': 'WanderersTroupe', 'slotKey': 'goblet'},
	'ConductorsTopHat': {'setKey': 'WanderersTroupe', 'slotKey': 'circlet'},
	'AyKhanoumsMyriad': {'setKey': 'FlowerOfParadiseLost', 'slotKey': 'flower'},
	'WiltingFeast': {'setKey': 'FlowerOfParadiseLost', 'slotKey': 'plume'},
	'AMomentCongealed': {'setKey': 'FlowerOfParadiseLost', 'slotKey': 'sands'},
	'SecretKeepersMagicBottle': {'setKey': 'FlowerOfParadiseLost', 'slotKey': 'goblet'},
	'AmethystCrown': {'setKey': 'FlowerOfParadiseLost', 'slotKey': 'circlet'},
	'TheFirstDaysoftheCityofKings': {'setKey': 'DesertPavilionChronicle', 'slotKey': 'flower'},
	'EndoftheGoldenRealm': {'setKey': 'DesertPavilionChronicle', 'slotKey': 'plume'},
	'TimepieceoftheLostPath': {'setKey': 'DesertPavilionChronicle', 'slotKey': 'sands'},
	'DefenderoftheEnchantingDream': {'setKey': 'DesertPavilionChronicle', 'slotKey': 'goblet'},
	'LegacyoftheDesertHighBorn': {'setKey': 'DesertPavilionChronicle', 'slotKey': 'circlet'},
	"OdysseanFlower": {'setKey': 'NymphsDream', 'slotKey': 'flower'},
	"WickedMagesPlumule": {'setKey': 'NymphsDream', 'slotKey': 'plume'},
	"NymphsConstancy": {'setKey': 'NymphsDream', 'slotKey': 'sands'},
	"HeroesTeaParty": {'setKey': 'NymphsDream', 'slotKey': 'goblet'},
	"FellDragonsMonocle": {'setKey': 'NymphsDream', 'slotKey': 'circlet'},
	"StamenofKhvarenasOrigin": {'setKey': 'VourukashasGlow', 'slotKey': 'flower'},
	"VibrantPinion": {'setKey': 'VourukashasGlow', 'slotKey': 'plume'},
	"AncientAbscission": {'setKey': 'VourukashasGlow', 'slotKey': 'sands'},
	"FeastofBoundlessJoy": {'setKey': 'VourukashasGlow', 'slotKey': 'goblet'},
	"HeartofKhvarenasBrilliance": {'setKey': 'VourukashasGlow', 'slotKey': 'circlet'},
}

